[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait ={ workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }