[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dioxus = "0.5.6"
dioxus-web = "0.5.6"
wasm-bindgen = "0.2"
web-sys = "0.3"
js-sys = "0.3"
core = { path = "../core" }
serde = { workspace = true }
serde_json = { workspace = true }